# Generated by Django 5.2.6 on 2025-12-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoHolistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_object_id', models.UUIDField()),
                ('destino_object_id', models.UUIDField()),
                ('tipo', models.CharField(choices=[('CAUSA_FISICA', 'Causa Física'), ('CAUSA_EMOCIONAL', 'Causa Emocional'), ('INIBE', 'Inibe/Bloqueia'), ('ESTIMULA', 'Estimula/Ativa'), ('SIMBOLIZA', 'Simboliza/Representa'), ('CURA', 'Cura/Trata'), ('AGRAVA', 'Agrava/Piora'), ('CORRELACAO', 'Correlação Direta')], max_length=50)),
                ('descricao', models.TextField(help_text='Explicação científica ou esotérica da conexão')),
                ('forca', models.IntegerField(default=5, help_text='Força da conexão de 1 a 10')),
                ('fonte', models.CharField(default='Medicina Integrativa', max_length=100)),
                ('destino_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('origem_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
    ]
