# Generated by Django 5.2.6 on 2025-12-27 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo_biologico', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=20)),
                ('dosha_ayurveda', models.CharField(blank=True, help_text='Vata, Pitta, Kapha', max_length=50)),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('queixa_principal', models.TextField()),
                ('sintomas_emocionais', models.TextField(blank=True, help_text='Tristeza, ansiedade, raiva...')),
                ('diagnostico_ia', models.TextField(blank=True, verbose_name='Parecer do Oráculo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='pacientes.paciente')),
            ],
        ),
    ]
