# Generated by Django 5.2.6 on 2025-12-27 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquetipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('sombra', models.TextField(help_text='O lado negativo deste arquétipo')),
                ('luz', models.TextField(help_text='O lado positivo deste arquétipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emocao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('polaridade', models.CharField(choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa'), ('NEUTRA', 'Neutra')], max_length=20)),
                ('impacto_imediato', models.TextField(help_text='O que sente no corpo na hora?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('ondas_cerebrais', models.CharField(help_text='Alfa, Beta, Theta, Delta, Gama', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
