# Generated by Django 5.2.6 on 2025-12-27 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pensamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('padrao', models.CharField(max_length=200, verbose_name='Padrão de Pensamento')),
                ('categoria', models.CharField(choices=[('CRENCA_LIMITANTE', 'Crença Limitante'), ('AFIRMACAO', 'Afirmação Positiva'), ('RUMINACAO', 'Ruminação/Obsessão')], max_length=50)),
                ('frequencia_estimada', models.CharField(blank=True, help_text='Quantas vezes por dia isso ocorre em média na pessoa afetada', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
