# Generated by Django 5.2.6 on 2025-12-27 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chakra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('nome_sancrito', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meridiano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('elemento', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
