# Generated by Django 5.2.6 on 2025-12-27 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anatomia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HORMONIO', 'Hormônio'), ('NEUROTRANSMISSOR', 'Neurotransmissor'), ('NUTRIENTE', 'Nutriente/Vitamina'), ('TOXINA', 'Toxina'), ('MEDICAMENTO', 'Medicamento'), ('DROGA', 'Droga Recreativa')], max_length=50)),
                ('formula_quimica', models.CharField(blank=True, max_length=50)),
                ('meia_vida', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessoMetabolico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('orgaos_envolvidos', models.ManyToManyField(blank=True, to='anatomia.orgao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
