# Generated by Django 5.2.6 on 2025-12-27 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processometabolico',
            name='descricao_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='substancia',
            name='tipo',
            field=models.CharField(choices=[('HORMONIO', 'Hormônio'), ('NEUROTRANSMISSOR', 'Neurotransmissor'), ('NUTRIENTE', 'Nutriente/Vitamina'), ('TOXINA', 'Toxina'), ('MEDICAMENTO', 'Medicamento'), ('DROGA', 'Droga Recreativa'), ('FITOQUIMICO', 'Fitoquímico (Plantas)')], max_length=50),
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('CARBOIDRATO', 'Carboidrato'), ('PROTEINA_ANIMAL', 'Proteína Animal'), ('PROTEINA_VEGETAL', 'Proteína Vegetal'), ('GORDURA', 'Gordura/Óleo'), ('FRUTA', 'Fruta'), ('VEGETAL', 'Vegetal/Legume'), ('BEBIDA', 'Bebida'), ('PROCESSADO', 'Alimento Processado')], max_length=50)),
                ('natureza_energetica', models.CharField(choices=[('QUENTE', 'Quente (Yang)'), ('MORNO', 'Morno'), ('NEUTRO', 'Neutro'), ('FRESCO', 'Fresco'), ('FRIO', 'Frio (Yin)')], default='NEUTRO', help_text='Impacto térmico na MTC', max_length=50)),
                ('dosha_predominante', models.CharField(blank=True, help_text='Vata, Pitta, Kapha (Aumenta/Diminui)', max_length=50)),
                ('compostos_ativos', models.ManyToManyField(blank=True, related_name='encontrado_em', to='metabolismo.substancia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
