# Generated by Django 5.2.6 on 2025-12-27 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolismo', '0002_processometabolico_descricao_tecnica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancia',
            name='tipo',
            field=models.CharField(choices=[('HORMONIO', 'Hormônio'), ('NEUROTRANSMISSOR', 'Neurotransmissor'), ('NUTRIENTE', 'Nutriente/Vitamina'), ('MINERAL', 'Mineral'), ('TOXINA', 'Toxina'), ('MEDICAMENTO', 'Medicamento'), ('DROGA', 'Droga Recreativa'), ('FITOQUIMICO', 'Fitoquímico (Plantas)')], max_length=50),
        ),
        migrations.CreateModel(
            name='Desequilibrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FALTA', 'Falta/Deficiência'), ('EXCESSO', 'Excesso/Toxicidade')], max_length=20)),
                ('nome_condicao', models.CharField(blank=True, help_text='Nome médico da condição (Ex: Anemia)', max_length=100)),
                ('sintomas', models.TextField(help_text='Lista de sintomas separados por vírgula')),
                ('consequencias_holisticas', models.TextField(blank=True, help_text='Impacto na mente e energia')),
                ('substancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desequilibrios', to='metabolismo.substancia')),
            ],
        ),
    ]
