# Generated by Django 5.2.6 on 2025-12-27 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaCorporal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('funcao_principal', models.TextField()),
                ('cor_associada', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('funcao_biologica', models.TextField()),
                ('elemento_mtc', models.CharField(blank=True, choices=[('FOGO', 'Fogo'), ('TERRA', 'Terra'), ('METAL', 'Metal'), ('AGUA', 'Água'), ('MADEIRA', 'Madeira')], max_length=50)),
                ('horario_pico', models.CharField(blank=True, help_text='Horário do relógio biológico', max_length=50)),
                ('representacao_emocional', models.CharField(blank=True, help_text='Ex: O Fígado armazena a raiva', max_length=200)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos', to='anatomia.sistemacorporal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
