# Generated by Django 5.2.6 on 2025-12-27 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao_detalhada', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('frequencia_hz', models.FloatField(default=0.0, help_text='Vibração energética aproximada', verbose_name='Frequência Base (Hz)')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_geral', models.CharField(max_length=50)),
                ('tempo_vida_medio', models.CharField(blank=True, help_text='Ex: 120 dias', max_length=50)),
                ('funcao_micro', models.TextField(verbose_name='Função Celular')),
                ('encontrada_em', models.ManyToManyField(blank=True, related_name='tipos_celulares', to='anatomia.orgao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
