# Generated by Django 5.2.6 on 2025-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomia', '0002_celula'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='inervacao',
            field=models.CharField(blank=True, help_text='Ex: Nervo Axilar', max_length=200),
        ),
        migrations.AddField(
            model_name='orgao',
            name='insercao',
            field=models.CharField(blank=True, help_text='Ex: Úmero', max_length=200),
        ),
        migrations.AddField(
            model_name='orgao',
            name='origem',
            field=models.CharField(blank=True, help_text='Ex: Clavícula (Anatomia Muscular)', max_length=200),
        ),
        migrations.AddField(
            model_name='orgao',
            name='vascularizacao',
            field=models.CharField(blank=True, help_text='Ex: Artérias Circunflexas', max_length=200),
        ),
    ]
